site_name: Nautomation Prime - Under Contruction
site_description: Enterprise Cisco Logic, Explained Line-by-Line.
theme:
  name: material

nav:
  - Home: index.md
  - Custom Services: services.md
  - Deep Dives:
    - Introduction: deep-dives/index.md
  - Script Library:
    - Overview: scripts/index.md
